"""arcgis router plugin for PS-MCP."""

from .arcgis_service import arcgis_router

try:
    from ._version import __version__  # type: ignore[attr-defined]
except ImportError:  # pragma: no cover - generated by hatch-vcs at build time
    __version__ = "0.0.0+unknown"

__all__ = ["__version__", "arcgis_router"]
